const ACTION_TYPES = {
    FETCH_PRODUCTS:'FETCH_PRODUCTS',
    FETCH_PRODUCTS_SUCCESS:'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_ERROR:'FETCH_PRODUCTS_ERROR',

}

export default ACTION_TYPES